language: python
python:
  - "3.6"
  - "3.5"
  
os:
  - linux
  - osx
  
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=./
after_success:
  - codecov
