language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: '3.6'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: xenial
    python: '3.7'
  - os: linux
    dist: xenial
    python: '3.6'
  - os: linux
    dist: xenial
    python: '3.5'

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - python -m pytest --cov=./
after_success:
  - codecov
